// Mock data for the restaurant app
export const MOCK_LOCATIONS = [
  { id: 'timperley-altrincham', name: 'Timperley, Altrincham', slug: 'timperley-altrincham', address: 'Timperley, Altrincham', is_active: true },
  { id: 'howe-bridge-atherton', name: 'Howe Bridge, Atherton', slug: 'howe-bridge-atherton', address: 'Howe Bridge, Atherton', is_active: true },
  { id: 'chaddesden-derby', name: 'Chaddesden, Derby', slug: 'chaddesden-derby', address: 'Chaddesden, Derby', is_active: true },
  { id: 'oakmere-handforth', name: 'Oakmere, Handforth', slug: 'oakmere-handforth', address: 'Oakmere, Handforth', is_active: true },
  { id: 'willowmere-middlewich', name: 'Willowmere, Middlewich', slug: 'willowmere-middlewich', address: 'Willowmere, Middlewich', is_active: true },
];

export const MOCK_MENU_ITEMS = [
  // Timperley, Altrincham
  { id: '1', location_id: 'timperley-altrincham', name: 'Truffle Mushroom Risotto', subtitle: 'Creamy Arborio rice with wild mushrooms', description: 'A rich and creamy risotto made with Arborio rice, wild mushrooms, truffle oil, and Parmesan cheese.', price: 28.99, original_price: 32.99, image_url: 'https://images.unsplash.com/photo-1692348023709-47ff577f7277', image_alt: 'Creamy mushroom risotto garnished with fresh herbs', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: ['vegetarian', 'gluten-free'], tags: ['signature', 'premium'], featured: true, rating: 4.8, review_count: 124, prep_time: 25, is_available: true },
  { id: '2', location_id: 'timperley-altrincham', name: 'Grilled Atlantic Salmon', subtitle: 'Fresh salmon with lemon herb butter', description: 'Fresh Atlantic salmon grilled to perfection with seasonal vegetables and roasted potatoes.', price: 34.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1722865382854-c2ac135189f5', image_alt: 'Grilled salmon fillet with roasted vegetables', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: ['gluten-free', 'keto'], tags: ['healthy', 'protein-rich'], featured: false, rating: 4.6, review_count: 89, prep_time: 20, is_available: true },
  { id: '3', location_id: 'timperley-altrincham', name: 'Crispy Calamari Rings', subtitle: 'Golden fried squid with marinara', description: 'Fresh squid rings lightly battered and fried to golden perfection with house-made marinara sauce.', price: 16.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1639024469010-44d77e559f7d', image_alt: 'Golden-brown crispy calamari rings with marinara', category: 'appetizers', categories: ['lunch', 'appetizer'], dietary: [], tags: ['crispy', 'seafood'], featured: true, rating: 4.4, review_count: 156, prep_time: 12, is_available: true },
  { id: '4', location_id: 'timperley-altrincham', name: 'Classic Tiramisu', subtitle: 'Traditional Italian dessert', description: 'Layers of coffee-soaked ladyfingers and mascarpone cream, dusted with cocoa powder.', price: 12.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1712262582604-4cbafeeca156', image_alt: 'Slice of tiramisu with distinct layers', category: 'desserts', categories: ['dessert'], dietary: ['vegetarian'], tags: ['traditional', 'coffee'], featured: false, rating: 4.7, review_count: 203, prep_time: 5, is_available: true },
  { id: '5', location_id: 'timperley-altrincham', name: 'Craft Beer Selection', subtitle: 'Local brewery favorites', description: 'Rotating selection of craft beers from local breweries.', price: 8.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1565291133543-2c86c724f847', image_alt: 'Three different craft beer glasses', category: 'beverages', categories: ['beverage'], dietary: ['vegan'], tags: ['local', 'craft'], featured: true, rating: 4.3, review_count: 67, prep_time: 2, is_available: true },
  { id: '6', location_id: 'timperley-altrincham', name: 'Chocolate Lava Cake', subtitle: 'Warm cake with molten center', description: 'Decadent chocolate cake with a molten chocolate center, served with vanilla ice cream.', price: 11.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1457823622778-ccdb4b7aa62d', image_alt: 'Chocolate lava cake with molten chocolate flowing out', category: 'desserts', categories: ['dessert'], dietary: ['vegetarian'], tags: ['warm', 'chocolate'], featured: true, rating: 4.9, review_count: 287, prep_time: 8, is_available: true },
  { id: '7', location_id: 'timperley-altrincham', name: 'Buffalo Chicken Wings', subtitle: 'Spicy wings with blue cheese', description: 'Crispy chicken wings tossed in our signature buffalo sauce with celery sticks.', price: 15.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1624726175512-19b9baf9fbd1', image_alt: 'Golden-brown buffalo chicken wings', category: 'appetizers', categories: ['lunch', 'appetizer'], dietary: ['gluten-free'], tags: ['spicy', 'wings'], featured: false, rating: 4.3, review_count: 178, prep_time: 15, is_available: true },
  { id: '8', location_id: 'timperley-altrincham', name: 'Fresh Fruit Smoothie', subtitle: 'Blend of seasonal fruits', description: 'Refreshing smoothie made with seasonal fresh fruits, yogurt, and honey.', price: 7.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1662130187270-a4d52c700eb6', image_alt: 'Three colorful fruit smoothies in tall glasses', category: 'beverages', categories: ['breakfast', 'beverage'], dietary: ['vegetarian', 'gluten-free'], tags: ['healthy', 'fresh'], featured: false, rating: 4.1, review_count: 45, prep_time: 5, is_available: true },

  // Howe Bridge, Atherton
  { id: '9', location_id: 'howe-bridge-atherton', name: 'BBQ Pulled Pork Sandwich', subtitle: 'Slow-cooked pork with house BBQ sauce', description: 'Tender pulled pork slow-cooked for 12 hours and tossed in our signature BBQ sauce on a brioche bun.', price: 18.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1545196353-e431cf8d0803', image_alt: 'BBQ pulled pork sandwich on brioche bun', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: [], tags: ['bbq', 'comfort'], featured: true, rating: 4.4, review_count: 112, prep_time: 18, is_available: true },
  { id: '10', location_id: 'howe-bridge-atherton', name: 'Spinach & Artichoke Dip', subtitle: 'Creamy dip with tortilla chips', description: 'Our signature creamy spinach and artichoke dip served hot with crispy tortilla chips.', price: 14.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1703219339970-98cd69cc896f', image_alt: 'Creamy spinach artichoke dip in cast iron skillet', category: 'appetizers', categories: ['lunch', 'appetizer'], dietary: ['vegetarian'], tags: ['sharing', 'comfort'], featured: false, rating: 4.2, review_count: 134, prep_time: 10, is_available: true },
  { id: '11', location_id: 'howe-bridge-atherton', name: 'Mediterranean Quinoa Bowl', subtitle: 'Healthy grain bowl with fresh vegetables', description: 'Nutritious quinoa bowl topped with roasted vegetables, chickpeas, feta cheese, and tahini dressing.', price: 19.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf', image_alt: 'Colorful quinoa bowl with roasted vegetables', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: ['vegetarian', 'gluten-free'], tags: ['healthy', 'mediterranean'], featured: false, rating: 4.5, review_count: 91, prep_time: 15, is_available: true },
  { id: '12', location_id: 'howe-bridge-atherton', name: 'Vanilla Bean Creme Brulee', subtitle: 'Classic French dessert', description: 'Rich vanilla custard topped with caramelized sugar, served with fresh seasonal berries.', price: 13.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1607235780843-a196b94386b4', image_alt: 'Creme brulee in white ramekin with caramelized sugar', category: 'desserts', categories: ['dessert'], dietary: ['vegetarian', 'gluten-free'], tags: ['french', 'classic'], featured: false, rating: 4.6, review_count: 95, prep_time: 3, is_available: true },
  { id: '13', location_id: 'howe-bridge-atherton', name: 'Grilled Chicken Burger', subtitle: 'Juicy chicken with house sauce', description: 'Tender grilled chicken breast with lettuce, tomato, and our signature house sauce on a toasted bun.', price: 16.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd', image_alt: 'Grilled chicken burger with fresh toppings', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: [], tags: ['grilled', 'popular'], featured: true, rating: 4.5, review_count: 201, prep_time: 15, is_available: true },
  { id: '14', location_id: 'howe-bridge-atherton', name: 'Iced Latte', subtitle: 'Smooth cold coffee with milk', description: 'Freshly brewed espresso poured over ice with your choice of milk.', price: 5.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735', image_alt: 'Iced latte in tall glass with ice', category: 'beverages', categories: ['breakfast', 'beverage'], dietary: ['vegetarian'], tags: ['coffee', 'cold'], featured: true, rating: 4.7, review_count: 312, prep_time: 3, is_available: true },

  // Chaddesden, Derby
  { id: '15', location_id: 'chaddesden-derby', name: 'Fish and Chips', subtitle: 'Classic British favourite', description: 'Beer-battered cod fillet served with thick-cut chips, mushy peas, and tartar sauce.', price: 17.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23', image_alt: 'Classic fish and chips with mushy peas', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: [], tags: ['classic', 'british'], featured: true, rating: 4.7, review_count: 345, prep_time: 20, is_available: true },
  { id: '16', location_id: 'chaddesden-derby', name: 'Chicken Tikka Masala', subtitle: 'Rich and creamy curry', description: 'Tender chicken pieces in a rich, creamy tomato-based sauce with aromatic spices. Served with basmati rice.', price: 16.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641', image_alt: 'Chicken tikka masala with basmati rice', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: ['gluten-free'], tags: ['curry', 'spicy'], featured: true, rating: 4.8, review_count: 289, prep_time: 25, is_available: true },
  { id: '17', location_id: 'chaddesden-derby', name: 'Sticky Toffee Pudding', subtitle: 'Warm British classic', description: 'Moist sponge pudding drenched in warm toffee sauce, served with vanilla ice cream.', price: 9.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e', image_alt: 'Sticky toffee pudding with toffee sauce', category: 'desserts', categories: ['dessert'], dietary: ['vegetarian'], tags: ['british', 'warm'], featured: true, rating: 4.9, review_count: 198, prep_time: 10, is_available: true },
  { id: '18', location_id: 'chaddesden-derby', name: 'English Breakfast Tea', subtitle: 'Traditional loose-leaf brew', description: 'A proper cup of English Breakfast tea served with milk and your choice of sweetener.', price: 3.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc', image_alt: 'English breakfast tea in white ceramic cup', category: 'beverages', categories: ['breakfast', 'beverage'], dietary: ['vegan', 'gluten-free'], tags: ['tea', 'british'], featured: false, rating: 4.5, review_count: 156, prep_time: 5, is_available: true },

  // Oakmere, Handforth
  { id: '19', location_id: 'oakmere-handforth', name: 'Avocado Toast', subtitle: 'Smashed avocado on sourdough', description: 'Creamy smashed avocado on toasted sourdough with cherry tomatoes, feta, and a poached egg.', price: 13.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820', image_alt: 'Avocado toast on sourdough with poached egg', category: 'appetizers', categories: ['breakfast', 'mains'], dietary: ['vegetarian'], tags: ['healthy', 'brunch'], featured: true, rating: 4.6, review_count: 234, prep_time: 10, is_available: true },
  { id: '20', location_id: 'oakmere-handforth', name: 'Pesto Pasta', subtitle: 'Fresh basil pesto with linguine', description: 'Al dente linguine tossed in our house-made basil pesto with pine nuts and Parmesan shavings.', price: 15.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601', image_alt: 'Pesto pasta with pine nuts and parmesan', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: ['vegetarian'], tags: ['pasta', 'italian'], featured: true, rating: 4.5, review_count: 167, prep_time: 15, is_available: true },
  { id: '21', location_id: 'oakmere-handforth', name: 'Halloumi Fries', subtitle: 'Crispy fried halloumi with dip', description: 'Golden-fried halloumi sticks served with sweet chilli dipping sauce and fresh mint yoghurt.', price: 11.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950', image_alt: 'Crispy halloumi fries with dipping sauce', category: 'appetizers', categories: ['lunch', 'appetizer'], dietary: ['vegetarian', 'gluten-free'], tags: ['crispy', 'cheese'], featured: true, rating: 4.7, review_count: 289, prep_time: 10, is_available: true },
  { id: '22', location_id: 'oakmere-handforth', name: 'Matcha Latte', subtitle: 'Japanese green tea with steamed milk', description: 'Premium ceremonial grade matcha whisked with steamed oat milk. Available hot or iced.', price: 5.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a', image_alt: 'Matcha latte in ceramic cup with latte art', category: 'beverages', categories: ['breakfast', 'beverage'], dietary: ['vegan'], tags: ['matcha', 'healthy'], featured: false, rating: 4.5, review_count: 178, prep_time: 5, is_available: true },
  { id: '23', location_id: 'oakmere-handforth', name: 'Lemon Tart', subtitle: 'Zesty French-style tart', description: 'Crisp pastry shell filled with silky smooth lemon curd, topped with fresh raspberries and icing sugar.', price: 8.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13', image_alt: 'Lemon tart with raspberries and icing sugar', category: 'desserts', categories: ['dessert'], dietary: ['vegetarian'], tags: ['citrus', 'french'], featured: true, rating: 4.8, review_count: 156, prep_time: 5, is_available: true },

  // Willowmere, Middlewich
  { id: '24', location_id: 'willowmere-middlewich', name: 'Sunday Roast', subtitle: 'Traditional roast with all the trimmings', description: 'Slow-roasted beef served with roast potatoes, Yorkshire pudding, seasonal vegetables, and rich gravy.', price: 22.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947', image_alt: 'Traditional Sunday roast with Yorkshire pudding', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: [], tags: ['traditional', 'sunday'], featured: true, rating: 4.9, review_count: 412, prep_time: 35, is_available: true },
  { id: '25', location_id: 'willowmere-middlewich', name: 'Homemade Soup of the Day', subtitle: 'Fresh seasonal soup', description: "Our chef's daily soup made with fresh seasonal ingredients, served with crusty bread and butter.", price: 8.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554', image_alt: 'Bowl of homemade soup with crusty bread', category: 'appetizers', categories: ['lunch', 'dinner', 'appetizer'], dietary: ['vegetarian'], tags: ['seasonal', 'homemade'], featured: false, rating: 4.5, review_count: 234, prep_time: 10, is_available: true },
  { id: '26', location_id: 'willowmere-middlewich', name: 'Beef Lasagne', subtitle: 'Hearty Italian classic', description: 'Layers of slow-cooked beef ragu, bechamel sauce, and pasta sheets, topped with melted mozzarella.', price: 17.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3', image_alt: 'Beef lasagne with melted cheese on top', category: 'mains', categories: ['lunch', 'dinner', 'mains'], dietary: [], tags: ['italian', 'comfort'], featured: true, rating: 4.7, review_count: 198, prep_time: 25, is_available: true },
  { id: '27', location_id: 'willowmere-middlewich', name: 'Scones with Clotted Cream', subtitle: 'Traditional afternoon tea treat', description: 'Freshly baked plain and fruit scones served with clotted cream and strawberry jam.', price: 7.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35', image_alt: 'Freshly baked scones with clotted cream and jam', category: 'desserts', categories: ['breakfast', 'dessert'], dietary: ['vegetarian'], tags: ['afternoon-tea', 'british'], featured: true, rating: 4.8, review_count: 267, prep_time: 5, is_available: true },
  { id: '28', location_id: 'willowmere-middlewich', name: 'Hot Chocolate', subtitle: 'Rich and indulgent', description: 'Velvety hot chocolate made with premium Belgian chocolate, topped with whipped cream and marshmallows.', price: 4.99, original_price: null, image_url: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed', image_alt: 'Rich hot chocolate with whipped cream and marshmallows', category: 'beverages', categories: ['breakfast', 'beverage'], dietary: ['vegetarian'], tags: ['chocolate', 'warm'], featured: false, rating: 4.6, review_count: 189, prep_time: 5, is_available: true },
];
